name: flutter_unique_id
description: get flutter_unique_id
version: 0.0.6
homepage: "https://github.com/xucongyong/flutter_unique_id"
repository: "https://github.com/xucongyong/flutter_unique_id"

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.reverse.flutter_unique_id
        pluginClass: FlutterUniqueIdPlugin
      ios:
        pluginClass: FlutterUniqueIdPlugin

